export const ErrorCodes = {
  // Auth & Permissions
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  FORBIDDEN: "FORBIDDEN",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  PROFILE_SYNC_FAILED: "PROFILE_SYNC_FAILED",
  AUTH_PROVIDER_UNAVAILABLE: "AUTH_PROVIDER_UNAVAILABLE",

  // Generic / Validation
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  RATE_LIMITED: "RATE_LIMITED",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  TRANSACTION_CONFLICT: "TRANSACTION_CONFLICT",

  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ADMIN_SELF_LOCK_FORBIDDEN: "ADMIN_SELF_LOCK_FORBIDDEN",

  // Categories & Products
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_SLUG_EXISTS: "CATEGORY_SLUG_EXISTS",
  CATEGORY_IN_USE: "CATEGORY_IN_USE",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_SKU_EXISTS: "PRODUCT_SKU_EXISTS",
  PRODUCT_OUT_OF_STOCK: "PRODUCT_OUT_OF_STOCK",
  PRODUCT_IN_USE: "PRODUCT_IN_USE",

  // Cart & Order
  CART_ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
  CART_EMPTY: "CART_EMPTY",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_CANNOT_CANCEL: "ORDER_CANNOT_CANCEL",
  INVALID_ORDER_STATE_TRANSITION: "INVALID_ORDER_STATE_TRANSITION",

  // Invoices & Payments & Webhooks
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  SEPAY_SIGNATURE_INVALID: "SEPAY_SIGNATURE_INVALID",

  // Notifications & Chatbot
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  CHATBOT_CONVERSATION_NOT_FOUND: "CHATBOT_CONVERSATION_NOT_FOUND",
  CHATBOT_RATE_LIMITED: "CHATBOT_RATE_LIMITED",
  CHATBOT_PROVIDER_ERROR: "CHATBOT_PROVIDER_ERROR",
  CHATBOT_PROVIDER_TIMEOUT: "CHATBOT_PROVIDER_TIMEOUT",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
